const maitrise = [
    {
        _id: '1',
        section: 'mdg',
        unite:'mdg',
        title: 'Chef de Groupe',
        name: 'Anthony Jreige',
        image: '/assets/images/anthony-jreige.jpg',
        totem: 'dit Hulotte Désopilant',
        phone: '+961 123 456',
        email: 'anthony@mdg.com',
    },
    {
        _id: '2',
        section: 'mdg',
        unite:'mdg',
        title: 'Aumonier de Groupe',
        name: 'Frère Jean-Claude Abou-Atmeh',
        image: '/assets/images/frere-jean-claude.jpg',
        totem: 'dit Garo Altuiste',
        phone: '+961 123 456',
        email: 'fjc@mdg.com',
    },
    {
        _id: '3',
        section: 'mdg',
        unite:'mdg',
        title: 'Secrétaire de Groupe',
        name: 'Maroun Fahed',
        image: '/assets/images/maroun-fahed.jpg',
        totem: 'dit Hamadryas Laborieux',
        phone: '+961 123 456',
        email: 'maroun@mdg.com',
    },
    {
        _id: '4',
        section: 'meutes',
        unite:'mistral',
        title: 'Cheftaine',
        name: 'Emmanuelle Zovighian',
        image: '/assets/images/emma-zovighian.JPG',
        totem: 'dite Cobaye Radieux',
        phone: '+961 123 456',
        email: 'emma@mdg.com',
    },
    {
        _id: '5',
        section: 'meutes',
        unite:'mistral',
        title: 'Assitante',
        name: 'Sarah Chidiac',
        image: '/assets/images/sarah-chidiac.jpg',
        totem: '',
        phone: '+961 123 456',
        email: 'sarah@mdg.com',
    },
    {
        _id: '6',
        section: 'meutes',
        unite:'magma',
        title: 'Cheftaine',
        name: 'Jana Adaimy',
        image: '/assets/images/jana-adaimy.JPG',
        totem: 'dite Cobaye Radieux',
        phone: '+961 123 456',
        email: 'jana@mdg.com',
    },
    {
        _id: '7',
        section: 'meutes',
        unite:'magma',
        title: 'Assitante',
        name: 'Marielle Fahed',
        image: '/assets/images/marielle-fahed.JPG',
        totem: 'dite Xerus Hardie',
        phone: '+961 123 456',
        email: 'marielle@mdg.com',
    },
    {
        _id: '8',
        section: 'meutes',
        unite:'mistral',
        title: 'Cheftaine',
        name: 'Anna Kamar',
        image: '/assets/images/anna-kamar.jpg',
        totem: 'dite Nagor Consciencieuse',
        phone: '+961 123 456',
        email: 'anna@mdg.com',
    },
    {
        _id: '9',
        section: 'troupes',
        unite:'cascade',
        title: 'Cheftaine',
        name: 'Samantha el Khoury',
        image: '/assets/images/samantha-elkhoury.JPG',
        totem: 'dite Chickaree Enthousiaste',
        phone: '+961 123 456',
        email: 'samantha@mdg.com',
    },
    {
        _id: '10',
        section: 'troupes',
        unite:'cascade',
        title: 'Assitante',
        name: 'Nour Haddad',
        image: '/assets/images/nour-haddad.JPG',
        totem: 'dite Manati Diligente',
        phone: '+961 123 456',
        email: 'nour@mdg.com',
    },
    {
        _id: '11',
        section: 'troupes',
        unite:'cascade',
        title: 'Assitante',
        name: 'Cynthia Mnayar',
        image: '/assets/images/anna-kamar.jpg',
        totem: 'dite Chacma Enigmatique',
        phone: '+961 123 456',
        email: 'cynthia@mdg.com',
    },
    {
        _id: '12',
        section: 'troupes',
        unite:'etoile',
        title: 'Chef',
        name: 'Rudy Badawi',
        image: '/assets/images/rudy-badawi.JPG',
        totem: 'dit Alouatta Fiable',
        phone: '+961 123 456',
        email: 'rudy@mdg.com',
    },
    {
        _id: '13',
        section: 'troupes',
        unite:'etoile',
        title: 'Assitant',
        name: 'Carl Saad',
        image: '/assets/images/carl-saad.JPG',
        totem: 'dit Hyrax Inventif',
        phone: '+961 123 456',
        email: 'carl@mdg.com',
    },
    {
        _id: '14',
        section: 'troupes',
        unite:'etoile',
        title: 'Assitant',
        name: 'Michel Saloumi',
        image: '/assets/images/michel-saloume.JPG',
        totem: 'dit Beringues Humble',
        phone: '+961 123 456',
        email: 'michel@mdg.com',
    },
    {
        _id: '15',
        section: 'troupes',
        unite:'source',
        title: 'Chef',
        name: 'Jack Mouaykel',
        image: '/assets/images/jack-mouaykel.JPG',
        totem: 'dit Guanaco Hardi',
        phone: '+961 123 456',
        email: 'jack@mdg.com',
    },
    {
        _id: '16',
        section: 'troupes',
        unite:'source',
        title: 'Assitant',
        name: 'Alexis Hajj',
        image: '/assets/images/alexis-hajj.JPG',
        totem: 'dit Atèles Débrouillard',
        phone: '+961 123 456',
        email: 'alexis@mdg.com',
    },
    {
        _id: '17',
        section: 'troupes',
        unite:'source',
        title: 'Assitant',
        name: 'Charbel Abdallah',
        image: '/assets/images/charbel-abdallah.JPG',
        totem: 'dit Cariboux Fiable',
        phone: '+961 123 456',
        email: 'charbel@mdg.com',
    },
    {
        _id: '18',
        section: 'troupes',
        unite:'flamme',
        title: 'Chef',
        name: 'Fayssal Balhawan',
        image: '/assets/images/fayssal-balhawan.JPG',
        totem: 'dit Aguarà Compétant',
        phone: '+961 123 456',
        email: 'fayssal@mdg.com',
    },
    {
        _id: '19',
        section: 'troupes',
        unite:'flamme',
        title: 'Assitant',
        name: 'Mario Jreige',
        image: '/assets/images/mario-jreige.JPG',
        totem: 'dit Quokka Méthodique',
        phone: '+961 123 456',
        email: 'mario@mdg.com',
    },
    {
        _id: '20',
        section: 'troupes',
        unite:'flamme',
        title: 'Assitant',
        name: 'Michel Saliba',
        image: '/assets/images/michel-saliba.JPG',
        totem: 'dit Beringueï Fidèle',
        phone: '+961 123 456',
        email: 'michel@mdg.com',
    },
    {
        _id: '21',
        section: 'clans',
        unite:'pionnieres',
        title: 'Cheftaine',
        name: 'Sara Naji',
        image: '/assets/images/sara-naji.JPG',
        totem: 'dite Antilop Cabrée',
        phone: '+961 123 456',
        email: 'sara@mdg.com',
    },
    {
        _id: '22',
        section: 'clans',
        unite:'pionnieres',
        title: 'CE Cyclone',
        name: 'Maria Salameh',
        image: '/assets/images/maria-salameh.JPG',
        totem: 'dite Quokka Egaye',
        phone: '+961 123 456',
        email: 'maria@mdg.com',
    },
    {
        _id: '23',
        section: 'clans',
        unite:'pionnieres',
        title: 'CE Avalanche',
        name: 'Mira Harik',
        image: '/assets/images/mira-harik.JPG',
        totem: 'dite Gloutton Bien Veillante',
        phone: '+961 123 456',
        email: 'mira@mdg.com',
    },
    {
        _id: '24',
        section: 'clans',
        unite:'routiers',
        title: 'Chef',
        name: 'Elie Feghaly',
        image: '/assets/images/elie-feghali.JPG',
        totem: 'dit Mangouste Courtois',
        phone: '+961 123 456',
        email: 'elie@mdg.com',
    },
    {
        _id: '25',
        section: 'clans',
        unite:'routiers',
        title: 'CE Zénith',
        name: 'Fadi Suidan',
        image: '/assets/images/fadi-suidan.JPG',
        totem: 'dit Oryx Cordial',
        phone: '+961 123 456',
        email: 'fadi@mdg.com',
    },
    {
        _id: '26',
        section: 'clans',
        unite:'routiers',
        title: 'CE Ouragan',
        name: 'Eloy Nemer',
        image: '/assets/images/eloy-nemer.JPG',
        totem: 'dit Fossa Syndiqué',
        phone: '+961 123 456',
        email: 'eloy@mdg.com',
    },
    {
        _id: '27',
        section: 'clans',
        unite:'routiers',
        title: 'CE Pégase',
        name: 'Tarek Sukkar',
        image: '/assets/images/tarek-sukkar.JPG',
        totem: 'dit Bush Dog Laborieux',
        phone: '+961 123 456',
        email: 'tarek@mdg.com',
    },
    {
        _id: '21',
        section: 'clans',
        unite:'routiers',
        title: 'CE 109',
        name: 'Walid Zakhour',
        image: '/assets/images/walid-zakhour.JPG',
        totem: 'dit Bison Baraqué',
        phone: '+961 123 456',
        email: 'walid@mdg.com',
    },
]

export default maitrise