export const MAITRISE = [
    {
        id: 0,
        name: 'Anthony Jreige',
        image: '/',
        designation: 'Chef de Groupe',
        abbr: 'CG',
        featured: false,
    },
    {
        id: 1,
        name: 'Frère Jean Claude Abou Atmeh',
        image: '/',
        designation: 'Aumonier de Groupe',
        abbr: 'AUG',
        featured: false,
    },
    {
        id: 2,
        name: 'Maroun Fahed',
        image: '/',
        designation: 'Secrétaire de Groupe',
        abbr: 'SG',
        featured: false,
    },
    {
        id: 3,
        name: 'Emmanuelle Zovighian',
        image: '/',
        designation: 'Cheftaine Meute Mistral',
        abbr: 'CM Mistral',
        featured: false,
    },
    {
        id: 4,
        name: 'Jana Adaimy',
        image: '/',
        designation: 'Cheftaine Meute Magma',
        abbr: 'CM Magma',
        featured: false,
    },
    {
        id: 5,
        name: 'Anna Kamar',
        image: '/',
        designation: 'Cheftaine Meute Blizzard',
        abbr: 'CM Meute Blizzard',
        featured: false,
    },
    {
        id: 6,
        name: 'Samantha el Khoury',
        image: '/',
        designation: 'Cheftaine Troupe Cascade',
        abbr: 'CT Cascade',
        featured: false,
    },
    {
        id: 7,
        name: 'Rudy Badawi',
        image: '/',
        designation: 'Chef Troupe Etoile',
        abbr: 'CT Etoile',
        featured: false,
    },
    {
        id: 8,
        name: 'Jack Mouaykel',
        image: '/',
        designation: 'Chef Troupe Source',
        abbr: 'CT Source',
        featured: false,
    },
    {
        id: 9,
        name: 'Fayssal Balhawan',
        image: '/',
        designation: 'Chef Troupe Flamme',
        abbr: 'CT Flamme',
        featured: false,
    },
    {
        id: 10,
        name: 'Sara Naji',
        image: '/',
        designation: 'Cheftaine Clan des Pionnières',
        abbr: 'CC Pionnières',
        featured: false,
    },
    {
        id: 11,
        name: 'Elie Feghali',
        image: '/',
        designation: 'Chef Clan des Routiers',
        abbr: 'CC Routiers',
        featured: false,
    },

];